---
- hosts: all
  become: true
  tasks:
  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 pacage
    apt:
      name: apache2

  - name: Add PHP support for apache
    apt:
      name: libapache2-mod-php
